### ISSUE TITLE
多个表格导出到一个sheet支持吗

### ISSUE THREAD

**Issue by zxdeer** [Zheng-Changfu/table-exporter#10]

**Comment by Zheng-Changfu** [comment]
支持的，columns 和 data 是你自己定义的，并不会和特定表格绑定

**Comment by zxdeer** [comment]
是非感谢回复，还有个问题：

vue3里面报无法找到模块“table-excel”的声明文件

**Comment by zxdeer** [comment]
> 支持的，columns 和 data 是你自己定义的，并不会和特定表格绑定

我试了这样只能导出一个表格，比如一个sheet中上面一个表格，在尾部再加入一个表格这样咋导出，我看有个属性是tables，tables是指的是什么呢？

**Comment by Zheng-Changfu** [comment]
你可以看看 excel.js 多个 sheet 能不能合并到 一个 sheet 中去，这样可能是最简单的做法
