### ISSUE TITLE
合并表头的问题

### ISSUE THREAD

**Issue by jingyinzhou** [Zheng-Changfu/table-exporter#11]
合并表头的代码是例子中的代码： 
const column = [
      {
        title: '部门',
        children: [
          { title: 'name1', dataIndex: 'date' },
          { title: 'name2', dataIndex: 'name' },
        ],
      },
      { title: '省份', dataIndex: 'province' },
      { title: '市区', dataIndex: 'city' },
      { title: '地址', dataIndex: 'address' },
      { title: '邮编', dataIndex: 'zip' },
    ];
但是表头是如何跨行呢？想实现后面的效果
![1](https://github.com/user-attachments/assets/58d8acda-043c-486e-a7bf-5b90ab36b72b)
![2](https://github.com/user-attachments/assets/8e500666-a47c-4958-b20e-f0ad28e84d47)

**Comment by Zheng-Changfu** [comment]
> 合并表头的代码是例子中的代码：

什么意思，没明白

**Comment by jingyinzhou** [comment]
回复这么快。。。 字还没打完，点错了，发出去了

**Comment by jingyinzhou** [comment]
给出来的方法都是操作内容的，貌似没有操作表头的方法

**Comment by Zheng-Changfu** [comment]
你是想样式上表头的高度高一点么？

**Comment by Zheng-Changfu** [comment]
如果只是样式上想要高一点，你可以通过 setRowStyle 搞定，这里的 type 你可以限定为 header
![image](https://github.com/user-attachments/assets/649c72ef-f1e2-4aa6-a2c8-376e65f8da9b)

**Comment by jingyinzhou** [comment]
控件的title不填写，也会占一格，我想要实现的并不是高度高一些，您可以看我传的图，部门那里，我并不想要title，如果不填写title，也会在excel中占一格空白的格子
![3](https://github.com/user-attachments/assets/b1f2fcd2-f2b8-4aef-b178-baba5a81ba8f)

**Comment by Zheng-Changfu** [comment]
WX沟通吧 ZCF_614
