### ISSUE TITLE
太棒，用你们的插件轻松解决了导出的样式问题，感谢！

### ISSUE THREAD

**Issue by oy217** [Zheng-Changfu/table-exporter#3]
关于excle插入图片，字段的值写图片的地址就可以识别资源？对图片的地址有没有其他要求

**Comment by Zheng-Changfu** [comment]
图片路径参考demo，不允许跨域

**Comment by oy217** [comment]
![image](https://user-images.githubusercontent.com/22723737/166110845-9b0bec64-31b1-41b3-a1ea-a86b3ba4c67a.png)
设置样式合并最后几行，上传3张图片后发现每张图片都是重叠的，请问怎么解决 @Zheng-Changfu

**Comment by Zheng-Changfu** [comment]
> ![image](https://user-images.githubusercontent.com/22723737/166110845-9b0bec64-31b1-41b3-a1ea-a86b3ba4c67a.png) 设置样式合并最后几行，上传3张图片后发现每张图片都是重叠的，请问怎么解决 @Zheng-Changfu

这个是因为你图片数量太多，你的行高不够，你可以用 **setRowStyle**把行高设置一下就可以解决这个问题

new ElMapExportTable(
    {
      column,
      data,
      spanMethod: ({ row, column, rowIndex, columnIndex }) => {
        if (Array.isArray(row[column])) {
          return {
            rowspan: 3,
            colspan: 4
          }
        }
      },
      setRowStyle: ({ data, rowIndex, columnIndex, type }) => {
        if (rowIndex === 0 && type === 'main') {
          return {
            height: 350
          }
        }
      },
      setColumnStyle ({ columnIndex }) {
        if (columnIndex === 2) {
          return { width: 30 };
        }
      }
    }
