### ISSUE TITLE
冻结第一行

### ISSUE THREAD

**Issue by liuheo** [Zheng-Changfu/table-exporter#4]
想要冻结第一行应该怎么配置呢，我看是[exceljs](https://github.com/exceljs/exceljs/blob/master/README_zh.md#%E5%86%BB%E7%BB%93%E8%A7%86%E5%9B%BE)这样的

**Comment by Zheng-Changfu** [comment]
> 

https://github.com/Zheng-Changfu/table-exporter#11

**Comment by liuheo** [comment]
😂怪我眼拙没有看到，感谢了
