### ISSUE TITLE
大佬，数据为0的时候导出还是空白的

### ISSUE THREAD

**Issue by liuheo** [Zheng-Changfu/table-exporter#6]
原始数据：
![1456a59614af6085ea7f0fb889615bde.jpg](https://img.gejiba.com/images/1456a59614af6085ea7f0fb889615bde.jpg)

ElMapExportTable 打印的：
![fa4a624e39746520c5f4a96a44230b39.jpg](https://img.gejiba.com/images/fa4a624e39746520c5f4a96a44230b39.jpg)

得到的表格：
![7a716fd5c1cebcf2a346e3a2ac7ccda2.jpg](https://img.gejiba.com/images/24328792090c2678f2dc5328541b000d.jpg)

"table-excel": "^2.0.2"

**Comment by Xavier9896** [comment]
啊哈啊哈哈，我今天也碰到相同的问题，我转成 ‘0’ 可以了

**Comment by Zheng-Changfu** [comment]
是内部的一个 bug，最近比较忙，等我国庆的时候我会用 ts 重构一下这个包，把逻辑抽离出来，暂时解决的话可以转成字符串的 0

**Comment by liuheo** [comment]
> 啊哈啊哈哈，我今天也碰到相同的问题，我转成 ‘0’ 可以了

哈哈哈

**Comment by liuheo** [comment]
> 是内部的一个 bug，最近比较忙，等我国庆的时候我会用 ts 重构一下这个包，把逻辑抽离出来，暂时解决的话可以转成字符串的 0

好呢好呢，期待大佬

**Comment by Zheng-Changfu** [comment]
2.0.4 fixed
