### ISSUE TITLE
多sheet导出图片问题

### ISSUE THREAD

**Issue by herygaode** [Zheng-Changfu/table-exporter#7]
我用这个插件尝试导出多个sheet页的图片的时候, 但是只有第一个sheet页会获取图片,后续的sheet页都没有图片

**Comment by Zheng-Changfu** [comment]
能提供一下代码么，我本地测试没有问题

**Comment by herygaode** [comment]
前面那个问题其实图片已经导出来只是因为向下偏移了, 所以没看到. 这里我用的底部插入图片的方式,导出多个sheet页的时候呀,图片会往下偏移,

**Comment by Zheng-Changfu** [comment]
你可以提供一下代码

**Comment by Zheng-Changfu** [comment]
未提供代码
