### ISSUE TITLE
插入图片导不出来

### ISSUE THREAD

**Issue by HongDou666** [Zheng-Changfu/table-exporter#8]
将图片路径添加，导出表格时报错 环境 vite

**Comment by HongDou666** [comment]
将images 数组里面添加base64 file Blob  以及图片路径 都导不出来呢这是什么样的原因？

**Comment by Zheng-Changfu** [comment]
请提供最小化代码

**Comment by HongDou666** [comment]
@Zheng-Changfu 感谢回复！ 目前问题已查明 因项目中引用了mock导致此情况
