### ISSUE TITLE
想问下 table-excel 依赖 导出的全局变量的名字是什么呢 在源码哪里可以看吗（用作外链打包使用）

### ISSUE THREAD

**Issue by HongDou666** [Zheng-Changfu/table-exporter#9]

**Comment by Zheng-Changfu** [comment]
你是要打包成 umd 格式么

**Comment by HongDou666** [comment]
@Zheng-Changfu 像这样避免被打包到chunk 需要知道table-excel库对外暴露的变量
![Uploading 微信图片_20240619221045.png…]()

**Comment by HongDou666** [comment]
![微信图片_20240619221045](https://github.com/Zheng-Changfu/table-exporter/assets/93339366/e108be82-2dd7-4059-bd1a-caae1e5268be)

**Comment by HongDou666** [comment]
ElMapExportTable or ExcelJS ?

**Comment by Zheng-Changfu** [comment]
我没有打包成 umd 格式，只支持 es6 的方式，你要是想把你的库打包成umd格式的，你要改造我的代码，如果你只是想排除掉我的依赖不被打包进去，你可以使用 extennals 配置
